---
# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/super-linter/super-linter
# Configuration file for super-linter example:
# .github/super-linter.env
# Configuration files for individual linters should be placed in .github/linters

name: Lint Code Base

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      full_scan:
        type: boolean
        default: false
        required: false
        description: "Lint all codebase"
permissions:
  contents: read

jobs:
  super-linter:
    name: "Lint Code Base"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - name: "Get the common linters configuration"
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: main # 463-fix-false-green-json-validation-in-shared-super-linter-config # main # fix/superlinter-config
        repository: netcracker/.github
        persist-credentials: false
        path: common-configs
        sparse-checkout: |
          config/linters
    - name: "Move configs"
      run: |
        cp --update=none -vRT ./common-configs/config/linters /tmp/linters
        rm -rf ./common-configs
      # To report GitHub Actions status checks
    - name: "Checkout code"
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
        persist-credentials: false
    - name: "Apply the common linters configuration"
      run: |
        mkdir -p ./.github/linters
        cp --update=none -vRT /tmp/linters ./.github/linters

    - name: "Load super-linter environment file"
      shell: bash
      run: |
        # shellcheck disable=2086
        if [ -f "${GITHUB_WORKSPACE}/.github/super-linter.env" ]; then
          echo "Applying local linter environment:"
          grep "\S" ${GITHUB_WORKSPACE}/.github/super-linter.env | grep -v "^#"
          grep "\S" ${GITHUB_WORKSPACE}/.github/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        elif [ -f "/tmp/linters/super-linter.env" ]; then
          echo "::warning:: Local linter environment file .github/super-linter.env is not found"
          echo "Applying common linter environment:"
          grep "\S" /tmp/linters/super-linter.env | grep -v "^#"
          grep "\S" /tmp/linters/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        fi

    - name: "Lint Code Base"
      id: super-linter
      uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.full_scan || false }}
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref || github.event.push.ref }}
        SAVE_SUPER_LINTER_OUTPUT: "true"
        SAVE_SUPER_LINTER_SUMMARY: "true"
        CREATE_LOG_FILE: "true"
        LOG_FILE: ${{ github.workspace }}/super-linter.log

    - name: Upload Super-Linter output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: super-linter-output
        path: ${{ github.workspace }}/super-linter-output
        if-no-files-found: warn
    - name: Collect skipped files
      if: always()
      run: |
        grep -B 1 -iE "File ignored because" \
        ${{ github.workspace }}/super-linter.log > skipped-files.txt
        if [ -s skipped-files.txt ]; then
          echo "### ⚠️ Skipped files due to missing configuration"
        else
          rm -f skipped-files.txt
        fi
    - name: Upload skipped files list
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: skipped-files
        path: ${{ github.workspace }}/skipped-files.txt
        if-no-files-found: warn
